# RAPPEL: eth0 est à vagrant, ne pas y toucher

- hosts: localhost
  remote_user: root
  tasks:

# Configurations Réseaux
# suppression de connexion “Wired connexion 1”
  - shell: nmcli connection del "Wired connection 1"
    ignore_errors: true
# suppression de connexion “Wired connexion 2”
  - shell: nmcli connection del "Wired connection 2"
    ignore_errors: true

  - name: Configuration de VM3-6/eth1 (LAN2-6)
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      method6: auto

  - name: Configuration de VM3-6/eth2 (LAN4)
    nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      state: present
      autoconnect: true
      ip4: 172.16.2.186/28

  - name: Configuration des routes vers LAN1, LAN2 et LAN3
    community.general.nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      routes4:
        - 172.16.2.128/28 172.16.2.183 # LAN1
        - 172.16.2.160/28 172.16.2.183 # LAN2
        - 172.16.2.144/28 172.16.2.183 # LAN3
      state: present


  # - name: Installer inetd
  #   package:
  #     name: inetutils-inetd
  #     state: present

  # - shell: update-inetd --add "echo stream tcp6 nowait nobody internal"

  # - name: Démarrer le service inetd
  #   service:
  #     name: inetutils-inetd
  #     state: started

  - name: Suppression de la passerelle par défaut
    shell: ip route del default
    ignore_errors: true

  - name: Activation explicite de la configuration eth1
    shell: nmcli con up "eth1 via ansible"

  - name: Activation explicite de la configuration eth2
    shell: nmcli con up "eth2 via ansible"
