# RAPPEL: eth0 est à vagrant, ne pas y toucher

- hosts: localhost
  remote_user: root
  tasks:

# Configurations Réseaux
# suppression de connexion “Wired connexion 1”
  - shell: nmcli connection del "Wired connection 1"
    ignore_errors: true

# suppression route par défaut (de vagrant)
  - shell: ip route del default
    ignore_errors: true # permet à ansible de continuer même en cas d'erreur

  - name: Configuration de VM3/eth1 (LAN4)
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip4: 172.16.2.183/28

  - name: Activation explicite de la configuration eth1
    shell: nmcli con up "eth1 via ansible"
