# RAPPEL: eth0 est à vagrant, ne pas y toucher

- hosts: localhost
  remote_user: root
  tasks:
    # Configurations Réseaux
    # suppression de connexion “Wired connexion 1”
    - shell: nmcli connection del "Wired connection 1"
      ignore_errors: true
    # suppression de connexion “Wired connexion 2”
    - shell: nmcli connection del "Wired connection 2"
      ignore_errors: true

    - name: Suppression de la passerelle par défaut
      shell: ip route del default
      ignore_errors: true

    - name: Configuration de VM1-6/eth1 (LAN1-6)
      nmcli:
        type: ethernet
        conn_name: eth1 via ansible
        ifname: eth1
        state: present
        ip6: fc00:1234:1::16

    - name: Configuration de VM1-6/eth2 (LAN3)
      nmcli:
        type: ethernet
        conn_name: eth2 via ansible
        ifname: eth2
        state: present
        autoconnect: true
        ip4: 172.16.2.156/28

    - name: Configuration de la route vers LAN4 via TUN0
      community.general.nmcli:
        type: ethernet
        conn_name: eth2 via ansible
        ifname: eth2
        routes4: 172.16.2.176/28 172.16.2.1
        state: present

    - name: Activation du routage IPv4
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: yes

    - name: Configuration de la route vers LAN2-6 via VM2-6
      community.general.nmcli:
        type: ethernet
        conn_name: eth1 via ansible
        ifname: eth1
        routes6: fc00:1234:2::/64 fc00:1234:1::26
        state: present

    - name: Activation explicite de la configuration eth1
      shell: nmcli con up "eth1 via ansible"

    - name: Activation explicite de la configuration eth2
      shell: nmcli con up "eth2 via ansible"
